# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(max_length=100)),
            ],
        ),
    ]
